### ISSUE TITLE
Missing Plugin Exception

### ISSUE THREAD

**Issue by stefanniedermaier** [josegonzalez/php-error-handlers#6]
I have a project using a local ThemePlugin
`cakephp/cakephp: 3.4.x` (the error occurs under `cakephp/cakephp: 3.5.0_RC1` too)
ThemePlugin in `/plugins/ThemeLight` folder
`composer.json`
```json
"autoload": {
    "psr-4": {
        "App\\": "src",
        "ThemeLight\\": "./plugins/ThemeLight/src"
    }
},
```

In `app.php` i added the following configuration to `Error`
```php
'config' => [
	'handlers' => [
		'NewrelicHandler' => [],
	],
],
```

In `bootstrap.php` i changed 
```php
$isCli = PHP_SAPI === 'cli';
if ($isCli) {
    (new \Josegonzalez\ErrorHandlers\Cake\ConsoleErrorHandler(Configure::read('Error')))->register();
} else {
    (new \Josegonzalez\ErrorHandlers\Cake\ErrorHandler(Configure::read('Error')))->register();
}
```

After doing so and loading the plugin I'm getting an exception
```php
Plugin::load('Josegonzalez/ErrorHandlers');
Plugin::load('ThemeLight', ['bootstrap' => false, 'routes' => false]);
Plugin::load('CsvView');
```

```
Fatal error: [Cake\Core\Exception\MissingPluginException] Plugin ThemeLight could not be found. 
#0 /var/www/user/project/public/vendor/cakephp/cakephp/src/Core/App.php(190): Cake\Core\Plugin::classPath('ThemeLight') 
#1 /var/www/user/project/public/vendor/cakephp/cakephp/src/View/View.php(1287): Cake\Core\App::path('Template', 'ThemeLight') 
#2 /var/www/user/project/public/vendor/cakephp/cakephp/src/View/View.php(1101): Cake\View\View->_paths(NULL) 
#3 /var/www/user/project/public/vendor/cakephp/cakephp/src/View/View.php(606): Cake\View\View->_getViewFileName('Error/error500') 
#4 /var/www/user/project/public/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(364): Cake\View\View->render('error500', 'error') 
#5 /var/www/user/project/public/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(341): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500') 
#6 /var/www/user/project/public/vendor/cakephp/cakephp/src/Error/Exception in /var/www/user/project/public/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 149
```

When i switch the plugins around
```php
Plugin::load('ThemeLight', ['bootstrap' => false, 'routes' => false]);
Plugin::load('Josegonzalez/ErrorHandlers');
Plugin::load('CsvView');
```
the error changes
```
Error: The application is trying to load a file from the Josegonzalez/ErrorHandlers plugin.

Make sure your plugin Josegonzalez/ErrorHandlers is in the /var/www/user/project/public/plugins/ directory and was loaded. 
```

**Comment by josegonzalez** [comment]
How did you install the plugin?

**Comment by stefanniedermaier** [comment]
I installed via composer and enabled manually in bootstrap.php

**Comment by josegonzalez** [comment]
Is ThemeLight the new plugin, or this plugin? Also, can you gist your entire composer.json file?

**Comment by stefanniedermaier** [comment]
This plugin was the newest installed
Gist:
https://gist.github.com/stefanniedermaier/4ccfadbd944a41eaca6041f7e7b55a59
